swagger: "2.0"
info:
  version: "1.0.0"
  title: "API de Estatísticas de Jogos"
  description: "API para consulta de estatísticas de jogos de tiro"
basePath: "/"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /:
    get:
      description: "Retorna uma mensagem de boas-vindas"
      responses:
        200:
          description: "Mensagem de boas-vindas"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "Hello World!"
  /deaths:
    get:
      description: "Retorna as estatísticas de mortes em jogo"
      responses:
        200:
          description: "Estatísticas de mortes"
          schema:
            $ref: "#/definitions/ResultType"
definitions:
  Mods:
    type: "object"
    properties:
      MOD_TRIGGER_HURT:
        type: "number"
      MOD_ROCKET_SPLASH:
        type: "number"
      MOD_FALLING:
        type: "number"
      MOD_ROCKET:
        type: "number"
      MOD_RAILGUN:
        type: "number"
      MOD_MACHINEGUN:
        type: "number"
      MOD_SHOTGUN:
        type: "number"
      MOD_TELEFRAG:
        type: "number"
      MOD_BFG_SPLASH:
        type: "number"
      MOD_BFG:
        type: "number"
      MOD_CRUSH:
        type: "number"
  ResultType:
    type: "object"
    properties:
      deaths:
        type: "number"
      world:
        type: "object"
        properties:
          kills:
            type: "number"
      killsBetweenPlayers:
        type: "number"
      causes:
        $ref: "#/definitions/Mods"
